### ISSUE TITLE
test_date_index fails on certain modin versions

### ISSUE THREAD

**Issue by valerieyip** [modin-project/modin-spreadsheet#39]
### Environment

* Operating System: OSX
* Python Version: `$ python --version` 3.8.5
* How did you install modin-spreadsheet: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list` (please include modin-spreadsheet, notebook, and jupyterlab versions)
* Jupyter lab packages (if applicable): `$ jupyter labextension list`

### Description of Issue
test_date_index fails on certain modin issues:
0.8.1, 0.8.2, 0.9.1 works
0.8.3, 0.9.0 does not work

### Reproduction Steps

pytest -k test_date_index

### What steps have you taken to resolve this already?

Tried the modin versions above

### Anything else?

problem appears to come from & operator between filtered panda dataframes with the same index for all rows. (`combined_condition = combined_condition & c` on line 1476 of grid.py) In versions that fail, the result of the & has excess rows (e.g. a 4 row dataframe becomes 16 rows)
...

**Comment by richardlin047** [comment]
According to @devin-petersohn , this occurs because of Pandas being inconsistent and the `&` operator on the series causes a cross-join. Fixed in 0.9.1 release of Modin
